import type { Event } from "@/lib/schema";

// Echte österreichische AI-Events als Demo-Daten
export const DEMO_EVENTS: Event[] = [
  {
    id: 1,
    title: "AI Tinkerers Vienna — July 2026",
    date: "2026-07-15",
    location: "Wien, Österreich",
    category: "Meetup",
    score: 4.7,
    ratingCount: 23,
    url: "https://vienna.aitinkerers.org",
    source: "meetup", description: null, imageUrl: null,
    status: "upcoming",
    confirmed: true,
    createdAt: new Date("2026-06-01"),
  },
  {
    id: 2,
    title: "ESSAI 2026: European Summer School on AI",
    date: "2026-07-06",
    location: "Wien, Österreich",
    category: "Conference",
    score: 4.2,
    ratingCount: 8,
    url: "https://www.asai.ac.at/en/events",
    source: "google", description: null, imageUrl: null,
    status: "upcoming",
    confirmed: true,
    createdAt: new Date("2026-06-01"),
  },
  {
    id: 3,
    title: "AIM Hackathon: Personal & Trustworthy Autonomous Agents",
    date: "2026-08-20",
    location: "Wien, Österreich",
    category: "Hackathon",
    score: null,
    ratingCount: 0,
    url: "https://ai-mission.eu/hackathon.html",
    source: "google", description: null, imageUrl: null,
    status: "upcoming",
    confirmed: true,
    createdAt: new Date("2026-06-01"),
  },
  {
    id: 4,
    title: "AI Breakfast Vienna — AI Austria Meetup",
    date: "2026-07-03",
    location: "Wien, Österreich",
    category: "Networking",
    score: 5.0,
    ratingCount: 41,
    url: "https://www.meetup.com/ai-austria/",
    source: "meetup", description: null, imageUrl: null,
    status: "upcoming",
    confirmed: true,
    createdAt: new Date("2026-06-01"),
  },
  {
    id: 5,
    title: "Digital Humanism Conference 2026",
    date: "2026-06-24",
    location: "Wien, Österreich",
    category: "Conference",
    score: 3.8,
    ratingCount: 5,
    url: "https://digitalhumanism.at/en/events-en/",
    source: "google", description: null, imageUrl: null,
    status: "past",
    confirmed: true,
    createdAt: new Date("2026-05-01"),
  },
  {
    id: 6,
    title: "Machine Learning Engineer Meetup Linz",
    date: "2026-07-22",
    location: "Linz, Österreich",
    category: "Meetup",
    score: null,
    ratingCount: 0,
    url: "https://www.meetup.com/ai-austria/",
    source: "meetup", description: null, imageUrl: null,
    status: "upcoming",
    confirmed: true,
    createdAt: new Date("2026-06-15"),
  },
];
